### ISSUE TITLE
Weird errors and tool working stopped

### ISSUE THREAD

**Issue by balook** [dustico/dusti-lock#3]
invalid character '}' looking for beginning of object key string
2022/02/16 06:51:14 invalid character '}' looking for beginning of object key string

**Comment by jossef** [comment]
@balook thanks for reporting 🙏 

Seems by the error message this is a JSON parse error which makes sense since this tool parses your package.json file(s).

Can you please share if your project's JSON (package.json) file(s) are valid? [using jq](https://stackoverflow.com/a/46955018/3191896)

**Comment by jossef** [comment]
Kindly provide more information. Closing this Issue until then
