### ISSUE TITLE
can`t install: " no Go files in /home/user" . Help please :(

### ISSUE THREAD

**Issue by ivanred** [dustico/dusti-lock#4]

**Comment by jossef** [comment]
Hi @ivanred 

Assuming you might cloned the repo into `/home/user` and skipped the `cd` into `dustilock` directory. You should do:
``` 
git clone https://github.com/Checkmarx/dustilock
cd dustilock
go build
```

LMK if this does not resolve your issue. Best if you can provide the command you executed
